### ISSUE TITLE
Allow self closing tags on vue template

### ISSUE THREAD

**Issue by fsblemos** [glorious-codes/glorious-pitsby#116]
When documenting a vue component with a self closing tag on template, it is not parsed correctly.

Reading [this](https://github.com/vuejs/vue/issues/1036) related issue, it seems to be a limitation when using dom templates directly:

> It works ever since Vue 2.0, because that version uses a virtual dom.
> The only exception are templates that are defined in an actual .html document.

https://github.com/vuejs/vue/issues/1036#issuecomment-485133392

I would suggest changes the way vue components are mounted:

https://github.com/glorious-codes/glorious-pitsby/blob/8e10b5b9ecfbc79d42d23ec1886542da14f89103/src/webapp/scripts/services/vue-component-builder.js#L6-L11

to something like this, by passing the template for the vue constructor and only [mounting](https://vuejs.org/v2/api/#vm-mount) on container:

```js
const options = { template, ...controller };
const vm = new Vue(options).$mount(container);
```

**Comment by rafaelcamargo** [comment]
Seems interesting and very simple to implement. I'll give it a try 👍
