### ISSUE TITLE
Support for dark theme

### ISSUE THREAD

**Issue by Dav2070** [glorious-codes/glorious-pitsby#235]
Hey Rafael,

I'm currently working on implementing a dark theme for my components. It would be great to have dark theme support in Pitsby, so I can develop and test the dark styles of my components directly in Pitsby.

Here are my suggestions for a dark theme in Pitsby:
- Add a simple global switch in Pitsby to change between dark and light theme
- Add a setting in the config file to enable the theme switch
- If the theme switch is enabled, automatically use the dark theme if the browser of the user is set to dark, using the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query
- Use the [color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) CSS property to set the appearance of the Pitsby UI

I think using prefers-color-scheme and the color-scheme property is the most standard way to set the appearance of Pitsby and the components, without the need for any custom JS implementation. I'm also using this approach in my component library, but I don't know how most other devs are implementing dark styles, so if you have a better way to do this, let me know.

**Comment by rafaelcamargo** [comment]
Hey David!

Nice idea. I'll study what would be the simplest possible way of implementing this and then I share here with you.
I didn't know about `prefers-color-scheme` and `color-scheme`. I'll give a look into that. At first glance, that seems very interesting :v:

**Comment by Dav2070** [comment]
Hey Rafael,
just some corrections after doing more research on the topic:

The prefers-color-scheme media query only works with the theme of the browser / OS. Which means you can't override the theme of the page using color-scheme.

Additionally, the color-scheme property changes only the user agent styles sent by the browser. So if you set color-scheme to dark on a simple HTML page without any additional styles, the page and the elements will appear dark.

So it's not possible to change the appearance of Pitsby using color-scheme. It would require a non-standard way to solve this issue, but I will leave this to you and your own research for now. Sorry for the confusion!

These two articles on this topic are very interesting:
- [prefers-color-scheme: Hello darkness, my old friend](https://web.dev/prefers-color-scheme/)
- [Improved dark mode default styling with the color-scheme CSS property and the corresponding meta tag](https://web.dev/color-scheme/)

**Comment by Dav2070** [comment]
I think a combination of both methods makes the most sense. Setting the theme globally by calling a function, in addition to the theme property to override the theme for specific components. This way it's not necessary to set the theme for each component in the project specifically, but if needed it's possible to display components in different themes in the same project.

However, I assume only the global config would be relevant for Pitsby, at least initially.

---

In my component lib, setting the theme globally looks like this:
```
import { setTheme } from 'dav-ui-components'
setTheme('dark')
```
So it's almost the same as in your suggestion.

I think the most simple way to add this feature were to add an event to Pitsby for the theme change. This makes sure all component libraries will be able to make use of this feature without the need to adapt to a specific way of setting the theme.

I imagine something like this, e.g. in the Pitsby config file (but I'm not sure if this is even possible there):
```
module.exports = {
  onThemeChange: (theme) => {
    // Set the theme of the component lib
    setTheme(theme)
  }
  // ...
}
```

**Comment by rafaelcamargo** [comment]
Hey @Dav2070! Perfect. I have been working on a [project](https://github.com/rafaelcamargo/bordiple) that I'm going to launch next Wednesday (28), so from the next Friday onwards, I'll finally dedicate myself to implement this feature.

I liked very much your suggestion. Perhaps I will end up naming things slightly different, but the core idea is totally that.

As soon as I have a first alpha version for this feature, I'll ping you here 👍

**Comment by rafaelcamargo** [comment]
Hey @Dav2070! Version **1.35.0** just released :v:

The final API got very close to what you had suggested:
``` javascript
module.exports = {
  // You can optionally control Pitsby's color scheme (light/dark).
  colorScheme: {
    // In addition, you can set the color scheme used on Pitsby's first render.
    initial: 'dark',
    // If your components support both light/dark color schemes, you can
    // listen for changes made by the user and theme you components accordingly.
    onChange: function(scheme){
      // This function receives the color scheme (light/dark) just selected by the user.
      // With the selected color scheme in hands, you can appropriately adjust the
      // theme of you component library.
      //
      // HEADS UP! This function gets executed at browser's runtime, not Node's.
      // So you won't have access here to anything you eventually required in the
      // configuration file using commonjs.
    }
  }
}
```
I have just used this new feature on the Pitsby Demo Website and everything seems to have worked fine. Let me know if this API also works for you 👍 

At last, I'd like to thank you for your feature request. Implementing this new functionality, I learned **A LOT** about *color schemes* and will certainly apply all this knowledge in my other personal projects too. Thank you very much, buddy! 🎉

**Comment by Dav2070** [comment]
Thank you, the dark mode on Pitsby looks gorgeous!

**Comment by Dav2070** [comment]
Hey @rafaelcamargo, I did finally find the time to try this feature in my project. But I encountered an interesting bug: All quotation marks are removed from the code in the onChange function in the config file. My code looks like this:

![image](https://github.com/glorious-codes/glorious-pitsby/assets/16546287/227d6a84-3f14-45fc-a623-d8c87ba6c9f7)

This results in the following code in the HTML document:

![image](https://github.com/glorious-codes/glorious-pitsby/assets/16546287/8c767797-eea0-42e8-b964-dc48c09afcbd)

This seems to be caused here, as far as I can tell:
https://github.com/glorious-codes/glorious-pitsby/blob/master/src/cli/services/webapp-html-index-generator.js#L154

**Comment by rafaelcamargo** [comment]
Oh, well noticed, @Dav2070!

I'll try to fix this issue tonight and as soon I release a patch, I'll let you know 👍

**Comment by rafaelcamargo** [comment]
Hey, @Dav2070! Version `1.36.1` containing the necessary fix has just been published. Let me know if it works for you.

**Comment by Dav2070** [comment]
Perfect, thank you!
